# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d997b48fbe52645ec106c04aac86288b85c892a4b740f98f946228a00a48c5f19d79ec9beb07cb65a7df0cac9cfd846b4c805cb0614bfcc2b18e49836c160c

test:
  secret_key_base: 7e6b968a4005d787047dc8e4a9e522dd2ded24861371a3887180478cac70672898118d12c87d09e05b1c0e7b820729869fdf8be0cf46c09ac9313eb62a9598a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
